# Generated by Django 2.2.13 on 2020-06-11 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0004_hghghgh_jhgskajgsdkjfga"),
    ]

    operations = [
        migrations.RemoveField(model_name="hghghgh", name="jhgskajgsdkjfga",),
        migrations.AddField(
            model_name="hghghgh",
            name="dfgsfs",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hghghgh_dfgsfs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hghghgh",
            name="dfssdgsdf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hghghgh_dfssdgsdf",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hghghgh",
            name="sfdgsdfg",
            field=models.ManyToManyField(
                blank=True, related_name="hghghgh_sfdgsdfg", to="home.Hghghgh"
            ),
        ),
    ]
