# Generated by Django 2.2.13 on 2020-06-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_auto_20200611_1432"),
    ]

    operations = [
        migrations.RemoveField(model_name="hghghgh", name="dfgsfs",),
        migrations.RemoveField(model_name="hghghgh", name="dfssdgsdf",),
        migrations.RemoveField(model_name="hghghgh", name="sfdgsdfg",),
    ]
