# Generated by Django 2.2.13 on 2020-06-11 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_auto_20200611_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='adgsfdgs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homepage_adgsfdgs', to=settings.AUTH_USER_MODEL),
        ),
    ]
